--liquibase formatted sql

--changeset webmakaka:1

    create table monkeys (
       id integer generated by default as identity,
        address varchar(100),
        name varchar(100),
        primary key (id)
    );

--rollback drop table monkeys;


--changeset webmakaka:2


INSERT INTO MONKEYS (ID, NAME, ADDRESS) VALUES (1, 'Webmakaka1', 'Address1');
INSERT INTO MONKEYS (ID, NAME, ADDRESS) VALUES (2, 'Webmakaka2', 'Address2');
INSERT INTO MONKEYS (ID, NAME, ADDRESS) VALUES (3, 'Webmakaka3', 'Address3');
